export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const FILTER_CATEGORIES = 'FILTER_CATEGORIES';
export const FILTER_BY_PRICE = 'FILTER_BY_PRICE';
export const FILTER_BY_TRAIT = 'FILTER_BY_TRAIT';
export const SORT_PRODUCTS = 'SORT_PRODUCTS';